# Generated by Django 5.1.6 on 2026-02-01 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_contactmessage_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='نام محصول')),
                ('description', models.TextField(verbose_name='توضیح اصلی صفحه')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/', verbose_name='تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.product')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان سکشن')),
                ('content', models.TextField(blank=True, verbose_name='متن سکشن')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.product')),
            ],
            options={
                'verbose_name': 'سکشن محصول',
                'verbose_name_plural': 'سکشن\u200cهای محصول',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductSectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/sections/', verbose_name='تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.productsection')),
            ],
            options={
                'verbose_name': 'تصویر سکشن',
                'verbose_name_plural': 'تصاویر سکشن',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductSectionSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان مشخصه')),
                ('value', models.CharField(max_length=150, verbose_name='مقدار')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='pages.productsection')),
            ],
            options={
                'verbose_name': 'مشخصه فنی',
                'verbose_name_plural': 'مشخصات فنی',
            },
        ),
    ]
