# Generated by Django 5.1.6 on 2026-02-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_product_productimage_productsection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان مجوز / گواهی')),
                ('issuer', models.CharField(blank=True, max_length=150, verbose_name='مرجع صادرکننده')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='certifications/', verbose_name='تصویر مدرک')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'مجوز و گواهی',
                'verbose_name_plural': 'مجوزها و گواهی\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'verbose_name': 'درخواست تماس', 'verbose_name_plural': 'درخواست\u200cهای تماس'},
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='شماره تماس'),
        ),
    ]
