# Generated by Django 5.2.10 on 2026-02-01 22:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_certification_alter_lead_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'درخواست تماس', 'verbose_name_plural': 'درخواست\u200cهای تماس'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='product',
            name='specs_table',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='جدول مشخصات فنی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='توضیح محصول'),
        ),
        migrations.DeleteModel(
            name='ProductSectionSpec',
        ),
    ]
