# Generated by Django 5.2.10 on 2026-02-01 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_lead_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsectionimage',
            name='section',
        ),
        migrations.DeleteModel(
            name='ProductSection',
        ),
        migrations.DeleteModel(
            name='ProductSectionImage',
        ),
    ]
